### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/backport#1]
Ping me when you're done with the code, tests and readme. I'll do a little code review and publish your package on Packagist.

**Comment by mpociot** [comment]
Done with it @freekmurze 
As I mentioned - this package consists of the `illuminate/notifications` code for 99%.

**Comment by freekmurze** [comment]
I think it's better to stay as close to the original code as possible. So I'll just leave the code alone.

Only thing I've done it deleting second `composer.json` that was floating in the `Notifications` folder.
