### ISSUE TITLE
Call to undefined method Illuminate\Notifications\Messages\SlackMessage::from()

### ISSUE THREAD

**Issue by nglgzz** [laravel-notification-channels/backport#15]
Hey,

I've been trying to make some Slack notifications using Laravel 5.2, I'm following the docs, but I can't seem to change the bot's name and icon using the SlackMessage::from() method. Same goes for the SlackMessage::to() method to change the destination channel.

I tried to create those functions like they have [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Notifications/Messages/SlackMessage.php), the error disappears, but it doesn't actually change anything (the notification is unchanged), I'd suppose there's more files to change than just SlackMessage.php.

**Comment by arnoldmartinez** [comment]
https://laravel.com/docs/5.6/notifications#slack-notifications
