### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by marianvlad** [laravel-notification-channels/backport#8]
Hey, I'm trying to install notifications on laravel 5.2 and I have this error when I use the service provider.

```
PHP Fatal error:  Call to undefined method Illuminate\Bus\Dispatcher::maps() in /Users/vmg/Code/canyon/vendor/laravel-notification-channels/backport/src/Notifications/NotificationServiceProvider.php on line 29
```

**Comment by mpociot** [comment]
Fixed in commit https://github.com/laravel-notification-channels/backport/commit/d41a46c78dfe3ee320ad5b489317e61bc4eeb411

A new release (1.0.5) is already tagged.
